ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=5)

      DOUBLE PRECISION MDL_MH,MDL_MZ,MDL_MT,MDL_MW

      COMMON/MASSES/ MDL_MH,MDL_MZ,MDL_MT,MDL_MW


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_4, GC_5, GC_6, GC_30, GC_39,
     $  GC_54, GC_67, GC_68, GC_69, GC_71, GC_75, GC_76, GC_77, GC_79,
     $  GC_80, GC_84, GC_85, GC_90, GC_92, GC_93, GC_99

      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_4, GC_5, GC_6, GC_30,
     $  GC_39, GC_54, GC_67, GC_68, GC_69, GC_71, GC_75, GC_76, GC_77,
     $  GC_79, GC_80, GC_84, GC_85, GC_90, GC_92, GC_93, GC_99

