C     Diagram 2
      DATA MAPCONFIG(1)/2/
      DATA (IFOREST(I,-1,1),I=1,2)/1,3/
      DATA TPRID(-1,1)/24/
      DATA (SPROP(I,-1,1),I=1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/-1,4/
C     Diagram 3
      DATA MAPCONFIG(2)/3/
      DATA (IFOREST(I,-1,2),I=1,2)/1,3/
      DATA TPRID(-1,2)/251/
      DATA (SPROP(I,-1,2),I=1,1)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/-1,4/
C     Diagram 4
      DATA MAPCONFIG(3)/4/
      DATA (IFOREST(I,-1,3),I=1,2)/1,4/
      DATA TPRID(-1,3)/24/
      DATA (SPROP(I,-1,3),I=1,1)/0/
      DATA (IFOREST(I,-2,3),I=1,2)/-1,3/
C     Diagram 5
      DATA MAPCONFIG(4)/5/
      DATA (IFOREST(I,-1,4),I=1,2)/1,4/
      DATA TPRID(-1,4)/251/
      DATA (SPROP(I,-1,4),I=1,1)/0/
      DATA (IFOREST(I,-2,4),I=1,2)/-1,3/
C     Number of configs
      DATA MAPCONFIG(0)/4/
