      SUBROUTINE GETLESHOUCHE_AMUP_WPWMMUP
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER IDUP(NEXTERNAL,MAXPROC,MAXSPROC)
      INTEGER MOTHUP(2,NEXTERNAL)
      INTEGER ICOLUP(2,NEXTERNAL,MAXFLOW,MAXSPROC)
      COMMON/LESHOUCHE/IDUP,MOTHUP,ICOLUP
      IDUP(1:5,1,1)=[22,-13,24,-24,-13]
      MOTHUP(1,1: 5)=[  0,  0,  1,  1,  1]
      MOTHUP(2,1: 5)=[  0,  0,  2,  2,  2]
      RETURN
      END
