ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_qcd_qed_sm-muon'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_39 = ', GC_39
      WRITE(*,2) 'GC_54 = ', GC_54
      WRITE(*,2) 'GC_67 = ', GC_67
      WRITE(*,2) 'GC_68 = ', GC_68
      WRITE(*,2) 'GC_69 = ', GC_69
      WRITE(*,2) 'GC_71 = ', GC_71
      WRITE(*,2) 'GC_75 = ', GC_75
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_85 = ', GC_85
      WRITE(*,2) 'GC_90 = ', GC_90
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_93 = ', GC_93
      WRITE(*,2) 'GC_99 = ', GC_99
