ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      REAL*16 G
      COMMON/MP_STRONG/ G

      COMPLEX*32 GAL(2)
      COMMON/MP_WEAK/ GAL

      COMPLEX*32 MU_R
      COMMON/MP_RSCALE/ MU_R


      REAL*16 MDL_MH,MDL_MZ,MDL_MT,MDL_MW

      COMMON/MP_MASSES/ MDL_MH,MDL_MZ,MDL_MT,MDL_MW


      REAL*16 MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/MP_WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      COMPLEX*32 GC_1,GC_2,GC_3,GC_4,GC_5,GC_6,GC_30,GC_39,GC_54,GC_67
     $ ,GC_68,GC_69,GC_71,GC_75,GC_76,GC_77,GC_79,GC_80,GC_84,GC_85
     $ ,GC_90,GC_92,GC_93,GC_99

      COMMON/MP_COUPLINGS/ GC_1,GC_2,GC_3,GC_4,GC_5,GC_6,GC_30,GC_39
     $ ,GC_54,GC_67,GC_68,GC_69,GC_71,GC_75,GC_76,GC_77,GC_79,GC_80
     $ ,GC_84,GC_85,GC_90,GC_92,GC_93,GC_99


