ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      REAL*16 MP__G
      COMMON/MP_STRONG/ MP__G

      COMPLEX*32 MP__GAL(2)
      COMMON/MP_WEAK/ MP__GAL

      COMPLEX*32 MP__MU_R
      COMMON/MP_RSCALE/ MP__MU_R


      REAL*16 MP__MDL_MH,MP__MDL_MZ,MP__MDL_MT,MP__MDL_MW

      COMMON/MP_MASSES/ MP__MDL_MH,MP__MDL_MZ,MP__MDL_MT,MP__MDL_MW


      REAL*16 MP__MDL_WZ,MP__MDL_WH,MP__MDL_WW,MP__MDL_WT

      COMMON/MP_WIDTHS/ MP__MDL_WZ,MP__MDL_WH,MP__MDL_WW,MP__MDL_WT


      COMPLEX*32 MP__GC_1,MP__GC_2,MP__GC_3,MP__GC_4,MP__GC_5,MP__GC_6
     $ ,MP__GC_30,MP__GC_39,MP__GC_54,MP__GC_67,MP__GC_68,MP__GC_69
     $ ,MP__GC_71,MP__GC_75,MP__GC_76,MP__GC_77,MP__GC_79,MP__GC_80
     $ ,MP__GC_84,MP__GC_85,MP__GC_90,MP__GC_92,MP__GC_93,MP__GC_99

      COMMON/MP_COUPLINGS/ MP__GC_1,MP__GC_2,MP__GC_3,MP__GC_4
     $ ,MP__GC_5,MP__GC_6,MP__GC_30,MP__GC_39,MP__GC_54,MP__GC_67
     $ ,MP__GC_68,MP__GC_69,MP__GC_71,MP__GC_75,MP__GC_76,MP__GC_77
     $ ,MP__GC_79,MP__GC_80,MP__GC_84,MP__GC_85,MP__GC_90,MP__GC_92
     $ ,MP__GC_93,MP__GC_99


