      SUBROUTINE ME_ACCESSOR_HOOK(P,HEL,USER_ALPHAS,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=7)
      REAL*8 PI
      PARAMETER (PI= 3.141592653589793D0)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
      INTEGER HEL
      DOUBLE PRECISION USER_ALPHAS
CF2PY INTENT(IN)  :: P
CF2PY INTENT(IN)  :: HEL
CF2PY INTENT(IN)  :: USER_ALPHAS
CF2PY INTENT(OUT) :: ANS

      REAL*8 THIS_G

      INCLUDE 'coupl.inc'

      INTEGER DEN
      COMMON/IDEN/DEN

      INTEGER FL_FACTOR
      COMMON/FLAVOUR_FACTOR/FL_FACTOR
      FL_FACTOR = 1

C     ----------
C     BEGIN CODE
C     ----------

      IF (USER_ALPHAS.GT.0.0D0) THEN
        THIS_G = 2* DSQRT(USER_ALPHAS*PI)
        IF (THIS_G.NE.G) THEN
          G = THIS_G
          CALL UPDATE_AS_PARAM()
        ENDIF
      ENDIF

      CALL SMATRIXHEL_SPLITORDERS(P,HEL,ANS)

      END

      SUBROUTINE SMATRIX(P,ANS_SUMMED)
C     
C     Simple routine wrapper to provide the same interface for
C     backward compatibility for usage without split orders.
C     
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=7)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL), ANS_SUMMED
C     
C     VARIABLES
C     
      INTEGER I
      REAL*8 ANS(0:NSQAMPSO)

C     
C     BEGIN CODE
C     

      CALL SMATRIX_SPLITORDERS(P,ANS)
      ANS_SUMMED=ANS(0)

      END

      SUBROUTINE SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=144)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX(P,ANS)
      USERHEL=-1

      END

C     Give access to the helicity definition to the f2py API.
      SUBROUTINE GET_HELICITY_DEFINITIONS(NHEL_OUT)
      IMPLICIT NONE

      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NCOMB
      PARAMETER (NCOMB=144)
      INTEGER NHEL(NEXTERNAL,NCOMB)
      COMMON/BORN_HEL_CONFIGS/NHEL

      INTEGER NHEL_OUT(NCOMB,NEXTERNAL)
CF2PY INTENT(OUT) :: NHEL_OUT

      INTEGER I,J

      DO I=1,NEXTERNAL
        DO J=1,NCOMB
          NHEL_OUT(J,I) = NHEL(I,J)
        ENDDO
      ENDDO

      END

      SUBROUTINE SMATRIX_SPLITORDERS(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.5.3, 2017-03-09
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: mu- mu+ > w+ w- mu+ mu- QCD^2<=6 QED^2<=8 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=144)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=7)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE.,.TRUE.,.TRUE.,.TRUE.,.TRUE.,.TRUE.
     $ ,.TRUE./
      COMMON/CHOSEN_BORN_SQSO/CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
C     
C     LOCAL VARIABLES 
C     
      LOGICAL DO_INCLUDE_HEL_CONTRIB
      INTEGER NTRY
      REAL*8 T(NSQAMPSO), BUFF
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

      INTEGER HELICITIES(NEXTERNAL)

      INTEGER DEN
      COMMON/IDEN/DEN

      DOUBLE PRECISION AMP2(114)
      COMMON/TO_AMP2/AMP2
      DOUBLE PRECISION SUM_AMP2

      DATA IDEN/ 4/
C     
C     GLOBAL VARIABLES
C     
      INTEGER NHEL(NEXTERNAL,NCOMB)
      DATA (NHEL(I,   1),I=1,6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,   2),I=1,6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,   3),I=1,6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,   4),I=1,6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,   5),I=1,6) / 1,-1,-1, 0, 1,-1/
      DATA (NHEL(I,   6),I=1,6) / 1,-1,-1, 0, 1, 1/
      DATA (NHEL(I,   7),I=1,6) / 1,-1,-1, 0,-1,-1/
      DATA (NHEL(I,   8),I=1,6) / 1,-1,-1, 0,-1, 1/
      DATA (NHEL(I,   9),I=1,6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  10),I=1,6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  11),I=1,6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  12),I=1,6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  13),I=1,6) / 1,-1, 0, 1, 1,-1/
      DATA (NHEL(I,  14),I=1,6) / 1,-1, 0, 1, 1, 1/
      DATA (NHEL(I,  15),I=1,6) / 1,-1, 0, 1,-1,-1/
      DATA (NHEL(I,  16),I=1,6) / 1,-1, 0, 1,-1, 1/
      DATA (NHEL(I,  17),I=1,6) / 1,-1, 0, 0, 1,-1/
      DATA (NHEL(I,  18),I=1,6) / 1,-1, 0, 0, 1, 1/
      DATA (NHEL(I,  19),I=1,6) / 1,-1, 0, 0,-1,-1/
      DATA (NHEL(I,  20),I=1,6) / 1,-1, 0, 0,-1, 1/
      DATA (NHEL(I,  21),I=1,6) / 1,-1, 0,-1, 1,-1/
      DATA (NHEL(I,  22),I=1,6) / 1,-1, 0,-1, 1, 1/
      DATA (NHEL(I,  23),I=1,6) / 1,-1, 0,-1,-1,-1/
      DATA (NHEL(I,  24),I=1,6) / 1,-1, 0,-1,-1, 1/
      DATA (NHEL(I,  25),I=1,6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  26),I=1,6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  27),I=1,6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  28),I=1,6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  29),I=1,6) / 1,-1, 1, 0, 1,-1/
      DATA (NHEL(I,  30),I=1,6) / 1,-1, 1, 0, 1, 1/
      DATA (NHEL(I,  31),I=1,6) / 1,-1, 1, 0,-1,-1/
      DATA (NHEL(I,  32),I=1,6) / 1,-1, 1, 0,-1, 1/
      DATA (NHEL(I,  33),I=1,6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  34),I=1,6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  35),I=1,6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  36),I=1,6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  37),I=1,6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  38),I=1,6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  39),I=1,6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  40),I=1,6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  41),I=1,6) / 1, 1,-1, 0, 1,-1/
      DATA (NHEL(I,  42),I=1,6) / 1, 1,-1, 0, 1, 1/
      DATA (NHEL(I,  43),I=1,6) / 1, 1,-1, 0,-1,-1/
      DATA (NHEL(I,  44),I=1,6) / 1, 1,-1, 0,-1, 1/
      DATA (NHEL(I,  45),I=1,6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  46),I=1,6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  47),I=1,6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  48),I=1,6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  49),I=1,6) / 1, 1, 0, 1, 1,-1/
      DATA (NHEL(I,  50),I=1,6) / 1, 1, 0, 1, 1, 1/
      DATA (NHEL(I,  51),I=1,6) / 1, 1, 0, 1,-1,-1/
      DATA (NHEL(I,  52),I=1,6) / 1, 1, 0, 1,-1, 1/
      DATA (NHEL(I,  53),I=1,6) / 1, 1, 0, 0, 1,-1/
      DATA (NHEL(I,  54),I=1,6) / 1, 1, 0, 0, 1, 1/
      DATA (NHEL(I,  55),I=1,6) / 1, 1, 0, 0,-1,-1/
      DATA (NHEL(I,  56),I=1,6) / 1, 1, 0, 0,-1, 1/
      DATA (NHEL(I,  57),I=1,6) / 1, 1, 0,-1, 1,-1/
      DATA (NHEL(I,  58),I=1,6) / 1, 1, 0,-1, 1, 1/
      DATA (NHEL(I,  59),I=1,6) / 1, 1, 0,-1,-1,-1/
      DATA (NHEL(I,  60),I=1,6) / 1, 1, 0,-1,-1, 1/
      DATA (NHEL(I,  61),I=1,6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  62),I=1,6) / 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  63),I=1,6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  64),I=1,6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  65),I=1,6) / 1, 1, 1, 0, 1,-1/
      DATA (NHEL(I,  66),I=1,6) / 1, 1, 1, 0, 1, 1/
      DATA (NHEL(I,  67),I=1,6) / 1, 1, 1, 0,-1,-1/
      DATA (NHEL(I,  68),I=1,6) / 1, 1, 1, 0,-1, 1/
      DATA (NHEL(I,  69),I=1,6) / 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  70),I=1,6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  71),I=1,6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  72),I=1,6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  73),I=1,6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  74),I=1,6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  75),I=1,6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  76),I=1,6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  77),I=1,6) /-1,-1,-1, 0, 1,-1/
      DATA (NHEL(I,  78),I=1,6) /-1,-1,-1, 0, 1, 1/
      DATA (NHEL(I,  79),I=1,6) /-1,-1,-1, 0,-1,-1/
      DATA (NHEL(I,  80),I=1,6) /-1,-1,-1, 0,-1, 1/
      DATA (NHEL(I,  81),I=1,6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  82),I=1,6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  83),I=1,6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  84),I=1,6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  85),I=1,6) /-1,-1, 0, 1, 1,-1/
      DATA (NHEL(I,  86),I=1,6) /-1,-1, 0, 1, 1, 1/
      DATA (NHEL(I,  87),I=1,6) /-1,-1, 0, 1,-1,-1/
      DATA (NHEL(I,  88),I=1,6) /-1,-1, 0, 1,-1, 1/
      DATA (NHEL(I,  89),I=1,6) /-1,-1, 0, 0, 1,-1/
      DATA (NHEL(I,  90),I=1,6) /-1,-1, 0, 0, 1, 1/
      DATA (NHEL(I,  91),I=1,6) /-1,-1, 0, 0,-1,-1/
      DATA (NHEL(I,  92),I=1,6) /-1,-1, 0, 0,-1, 1/
      DATA (NHEL(I,  93),I=1,6) /-1,-1, 0,-1, 1,-1/
      DATA (NHEL(I,  94),I=1,6) /-1,-1, 0,-1, 1, 1/
      DATA (NHEL(I,  95),I=1,6) /-1,-1, 0,-1,-1,-1/
      DATA (NHEL(I,  96),I=1,6) /-1,-1, 0,-1,-1, 1/
      DATA (NHEL(I,  97),I=1,6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  98),I=1,6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  99),I=1,6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 100),I=1,6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 101),I=1,6) /-1,-1, 1, 0, 1,-1/
      DATA (NHEL(I, 102),I=1,6) /-1,-1, 1, 0, 1, 1/
      DATA (NHEL(I, 103),I=1,6) /-1,-1, 1, 0,-1,-1/
      DATA (NHEL(I, 104),I=1,6) /-1,-1, 1, 0,-1, 1/
      DATA (NHEL(I, 105),I=1,6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 106),I=1,6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 107),I=1,6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 108),I=1,6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 109),I=1,6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 110),I=1,6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 111),I=1,6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 112),I=1,6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 113),I=1,6) /-1, 1,-1, 0, 1,-1/
      DATA (NHEL(I, 114),I=1,6) /-1, 1,-1, 0, 1, 1/
      DATA (NHEL(I, 115),I=1,6) /-1, 1,-1, 0,-1,-1/
      DATA (NHEL(I, 116),I=1,6) /-1, 1,-1, 0,-1, 1/
      DATA (NHEL(I, 117),I=1,6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 118),I=1,6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 119),I=1,6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 120),I=1,6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 121),I=1,6) /-1, 1, 0, 1, 1,-1/
      DATA (NHEL(I, 122),I=1,6) /-1, 1, 0, 1, 1, 1/
      DATA (NHEL(I, 123),I=1,6) /-1, 1, 0, 1,-1,-1/
      DATA (NHEL(I, 124),I=1,6) /-1, 1, 0, 1,-1, 1/
      DATA (NHEL(I, 125),I=1,6) /-1, 1, 0, 0, 1,-1/
      DATA (NHEL(I, 126),I=1,6) /-1, 1, 0, 0, 1, 1/
      DATA (NHEL(I, 127),I=1,6) /-1, 1, 0, 0,-1,-1/
      DATA (NHEL(I, 128),I=1,6) /-1, 1, 0, 0,-1, 1/
      DATA (NHEL(I, 129),I=1,6) /-1, 1, 0,-1, 1,-1/
      DATA (NHEL(I, 130),I=1,6) /-1, 1, 0,-1, 1, 1/
      DATA (NHEL(I, 131),I=1,6) /-1, 1, 0,-1,-1,-1/
      DATA (NHEL(I, 132),I=1,6) /-1, 1, 0,-1,-1, 1/
      DATA (NHEL(I, 133),I=1,6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 134),I=1,6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 135),I=1,6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 136),I=1,6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 137),I=1,6) /-1, 1, 1, 0, 1,-1/
      DATA (NHEL(I, 138),I=1,6) /-1, 1, 1, 0, 1, 1/
      DATA (NHEL(I, 139),I=1,6) /-1, 1, 1, 0,-1,-1/
      DATA (NHEL(I, 140),I=1,6) /-1, 1, 1, 0,-1, 1/
      DATA (NHEL(I, 141),I=1,6) /-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 142),I=1,6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 143),I=1,6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 144),I=1,6) /-1, 1, 1,-1,-1, 1/
      COMMON/BORN_HEL_CONFIGS/NHEL

      INTEGER USERHEL
      DATA USERHEL/-1/
      COMMON/HELUSERCHOICE/USERHEL

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/
      COMMON/BORN_BEAM_POL/POLARIZATIONS



C     
C     FUNCTIONS
C     
      LOGICAL IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------

      DEN = IDEN




      NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
      DO I=1,NSQAMPSO
        ANS(I) = 0D0
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF


      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 2 .OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.-1.AND.
     $       (.NOT.IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            DO_INCLUDE_HEL_CONTRIB = (POLARIZATIONS(0,0).EQ.
     $       -1.OR.IS_BORN_HEL_SELECTED(IHEL))
            DO I=1,NEXTERNAL
              HELICITIES(I) = NHEL(I,IHEL)
            ENDDO
            CALL MATRIX(P ,HELICITIES(1),JC(1), T)
            BUFF=0D0
            DO I=1,NSQAMPSO
              IF(DO_INCLUDE_HEL_CONTRIB) THEN
                ANS(I)=ANS(I)+T(I)
              ENDIF
              BUFF=BUFF+T(I)
            ENDDO
            IF (BUFF .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS(0)=0.0D0

      DO I=1,NSQAMPSO
        ANS(I)=ANS(I)/DBLE(IDEN)
        IF (CHOSEN_SO_CONFIGS(I)) THEN
          ANS(0)=ANS(0)+ANS(I)
        ENDIF
      ENDDO
      IF(USERHEL.NE.-1) THEN
        DO I=0,NSQAMPSO
          ANS(I)=ANS(I)*HELAVGFACTOR
        ENDDO
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            DO I=0,NSQAMPSO
              ANS(I)=ANS(I)*BEAMS_HELAVGFACTOR(J)
              ANS(I)=ANS(I)/POLARIZATIONS(J,0)
            ENDDO
          ENDIF
        ENDDO
      ENDIF
      END

      SUBROUTINE SMATRIXHEL_SPLITORDERS(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=144)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=7)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
      INTEGER HEL

CF2PY INTENT(IN)  :: P
CF2PY INTENT(IN)  :: HEL
CF2PY INTENT(OUT) :: ANS

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL

      INTEGER DEN
      COMMON/IDEN/DEN
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX_SPLITORDERS(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE MATRIX(P,NHEL,IC,RES)

C     
C     Generated by MadGraph5_aMC@NLO v. 2.5.3, 2017-03-09
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: mu- mu+ > w+ w- mu+ mu- QCD^2<=6 QED^2<=8 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=114)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=25, NCOLOR=1)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=4, NSQAMPSO=7)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      REAL*8 RES(NSQAMPSO)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N, SQSOIND
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS)
      COMPLEX*16 JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      DOUBLE PRECISION AMP2(NGRAPHS),SUM_AMP2
      COMMON/TO_AMP2/AMP2
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  1) /    1/
C     1 ColorOne()
C     ----------
C     BEGIN CODE
C     ----------


      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL VXXXXX(P(0,3),MDL_MW,NHEL(3),+1*IC(3),W(1,3))
      CALL VXXXXX(P(0,4),MDL_MW,NHEL(4),+1*IC(4),W(1,4))
      CALL IXXXXX(P(0,5),ZERO,NHEL(5),-1*IC(5),W(1,5))
      CALL OXXXXX(P(0,6),ZERO,NHEL(6),+1*IC(6),W(1,6))
      CALL FFV2_2(W(1,1),W(1,4),GC_67,ZERO,ZERO,W(1,7))
      CALL FFV1P0_3(W(1,5),W(1,2),GC_3,ZERO,ZERO,W(1,8))
      CALL FFV2_2(W(1,7),W(1,3),GC_67,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,9),W(1,6),W(1,8),GC_3,AMP(1))
      CALL FFV2P0_3(W(1,7),W(1,6),GC_67,MDL_MW,MDL_WW,W(1,10))
C     Amplitude(s) for diagram number 2
      CALL VVV1_0(W(1,8),W(1,10),W(1,3),GC_4,AMP(2))
      CALL FFV2_4P0_3(W(1,5),W(1,2),GC_68,GC_77,MDL_MZ,MDL_WZ,W(1,11))
C     Amplitude(s) for diagram number 3
      CALL FFV2_4_0(W(1,9),W(1,6),W(1,11),GC_68,GC_77,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL VVV1_0(W(1,10),W(1,3),W(1,11),GC_71,AMP(4))
      CALL FFV2_1(W(1,6),W(1,3),GC_67,ZERO,ZERO,W(1,12))
C     Amplitude(s) for diagram number 5
      CALL FFV2_0(W(1,7),W(1,12),W(1,11),GC_80,AMP(5))
      CALL FFV1P0_3(W(1,5),W(1,6),GC_3,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 6
      CALL FFV1_0(W(1,9),W(1,2),W(1,13),GC_3,AMP(6))
      CALL FFV2P0_3(W(1,7),W(1,2),GC_67,MDL_MW,MDL_WW,W(1,14))
C     Amplitude(s) for diagram number 7
      CALL VVV1_0(W(1,13),W(1,14),W(1,3),GC_4,AMP(7))
      CALL FFV2_4P0_3(W(1,5),W(1,6),GC_68,GC_77,MDL_MZ,MDL_WZ,W(1,15))
C     Amplitude(s) for diagram number 8
      CALL FFV2_4_0(W(1,9),W(1,2),W(1,15),GC_68,GC_77,AMP(8))
C     Amplitude(s) for diagram number 9
      CALL VVV1_0(W(1,14),W(1,3),W(1,15),GC_71,AMP(9))
      CALL FFV2_1(W(1,2),W(1,3),GC_67,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 10
      CALL FFV2_0(W(1,7),W(1,9),W(1,15),GC_80,AMP(10))
C     Amplitude(s) for diagram number 11
      CALL FFV2_0(W(1,5),W(1,9),W(1,10),GC_67,AMP(11))
C     Amplitude(s) for diagram number 12
      CALL FFV2_0(W(1,5),W(1,12),W(1,14),GC_67,AMP(12))
      CALL FFV1P0_3(W(1,1),W(1,2),GC_3,ZERO,ZERO,W(1,14))
      CALL FFV2_2(W(1,5),W(1,4),GC_67,ZERO,ZERO,W(1,10))
      CALL VVV1P0_2(W(1,14),W(1,3),GC_4,MDL_MW,MDL_WW,W(1,7))
C     Amplitude(s) for diagram number 13
      CALL FFV2_0(W(1,10),W(1,6),W(1,7),GC_67,AMP(13))
      CALL FFV1_1(W(1,6),W(1,14),GC_3,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 14
      CALL FFV2_0(W(1,10),W(1,16),W(1,3),GC_67,AMP(14))
      CALL FFV2_4P0_3(W(1,1),W(1,2),GC_68,GC_77,MDL_MZ,MDL_WZ,W(1,17))
      CALL VVV1P0_1(W(1,3),W(1,17),GC_71,MDL_MW,MDL_WW,W(1,18))
C     Amplitude(s) for diagram number 15
      CALL FFV2_0(W(1,10),W(1,6),W(1,18),GC_67,AMP(15))
      CALL FFV2_4_1(W(1,6),W(1,17),GC_68,GC_77,ZERO,ZERO,W(1,19))
C     Amplitude(s) for diagram number 16
      CALL FFV2_0(W(1,10),W(1,19),W(1,3),GC_67,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFV2_0(W(1,10),W(1,12),W(1,17),GC_80,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL VVVV2_0(W(1,14),W(1,13),W(1,4),W(1,3),GC_5,AMP(18))
C     Amplitude(s) for diagram number 19
      CALL VVV1_0(W(1,13),W(1,4),W(1,7),GC_4,AMP(19))
      CALL VVS1_3(W(1,14),W(1,3),GC_93,MDL_MW,MDL_WW,W(1,20))
C     Amplitude(s) for diagram number 20
      CALL VVS1_0(W(1,13),W(1,4),W(1,20),GC_92,AMP(20))
      CALL VVV1P0_3(W(1,14),W(1,4),GC_4,MDL_MW,MDL_WW,W(1,21))
C     Amplitude(s) for diagram number 21
      CALL VVV1_0(W(1,13),W(1,21),W(1,3),GC_4,AMP(21))
      CALL VVS1_3(W(1,14),W(1,4),GC_92,MDL_MW,MDL_WW,W(1,22))
C     Amplitude(s) for diagram number 22
      CALL VVS1_0(W(1,13),W(1,3),W(1,22),GC_93,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL VVVV5_0(W(1,14),W(1,4),W(1,3),W(1,15),GC_75,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL VVV1_0(W(1,4),W(1,7),W(1,15),GC_71,AMP(24))
C     Amplitude(s) for diagram number 25
      CALL VVS1_0(W(1,4),W(1,15),W(1,20),GC_85,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL VVV1_0(W(1,21),W(1,3),W(1,15),GC_71,AMP(26))
C     Amplitude(s) for diagram number 27
      CALL VVS1_0(W(1,3),W(1,15),W(1,22),GC_84,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL VVVV5_0(W(1,13),W(1,4),W(1,3),W(1,17),GC_75,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL VVV1_0(W(1,13),W(1,4),W(1,18),GC_4,AMP(29))
      CALL VVS1_3(W(1,3),W(1,17),GC_84,MDL_MW,MDL_WW,W(1,22))
C     Amplitude(s) for diagram number 30
      CALL VVS1_0(W(1,13),W(1,4),W(1,22),GC_92,AMP(30))
      CALL VVV1P0_2(W(1,4),W(1,17),GC_71,MDL_MW,MDL_WW,W(1,20))
C     Amplitude(s) for diagram number 31
      CALL VVV1_0(W(1,13),W(1,20),W(1,3),GC_4,AMP(31))
      CALL VVS1_3(W(1,4),W(1,17),GC_85,MDL_MW,MDL_WW,W(1,7))
C     Amplitude(s) for diagram number 32
      CALL VVS1_0(W(1,13),W(1,3),W(1,7),GC_93,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL VVVV2_0(W(1,4),W(1,3),W(1,17),W(1,15),GC_54,AMP(33))
C     Amplitude(s) for diagram number 34
      CALL VVV1_0(W(1,4),W(1,18),W(1,15),GC_71,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL VVS1_0(W(1,4),W(1,15),W(1,22),GC_85,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL VVV1_0(W(1,20),W(1,3),W(1,15),GC_71,AMP(36))
C     Amplitude(s) for diagram number 37
      CALL VVS1_0(W(1,3),W(1,15),W(1,7),GC_84,AMP(37))
      CALL VVS1_3(W(1,4),W(1,3),GC_90,MDL_MH,MDL_WH,W(1,7))
C     Amplitude(s) for diagram number 38
      CALL VVS1_0(W(1,17),W(1,15),W(1,7),GC_99,AMP(38))
      CALL VVV1P0_1(W(1,4),W(1,3),GC_4,ZERO,ZERO,W(1,22))
      CALL FFV1_2(W(1,5),W(1,14),GC_3,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 39
      CALL FFV1_0(W(1,18),W(1,6),W(1,22),GC_3,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL FFV1_0(W(1,5),W(1,16),W(1,22),GC_3,AMP(40))
      CALL VVV1P0_3(W(1,4),W(1,3),GC_71,MDL_MZ,MDL_WZ,W(1,14))
C     Amplitude(s) for diagram number 41
      CALL FFV2_4_0(W(1,18),W(1,6),W(1,14),GC_68,GC_77,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFV2_4_0(W(1,5),W(1,16),W(1,14),GC_68,GC_77,AMP(42))
      CALL FFV2_4_2(W(1,5),W(1,17),GC_68,GC_77,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 43
      CALL FFV1_0(W(1,16),W(1,6),W(1,22),GC_3,AMP(43))
C     Amplitude(s) for diagram number 44
      CALL FFV1_0(W(1,5),W(1,19),W(1,22),GC_3,AMP(44))
C     Amplitude(s) for diagram number 45
      CALL FFV2_4_0(W(1,16),W(1,6),W(1,14),GC_68,GC_77,AMP(45))
C     Amplitude(s) for diagram number 46
      CALL FFV2_4_0(W(1,5),W(1,19),W(1,14),GC_68,GC_77,AMP(46))
C     Amplitude(s) for diagram number 47
      CALL FFV2_0(W(1,18),W(1,12),W(1,4),GC_67,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL FFV2_0(W(1,5),W(1,12),W(1,21),GC_67,AMP(48))
C     Amplitude(s) for diagram number 49
      CALL FFV2_0(W(1,16),W(1,12),W(1,4),GC_67,AMP(49))
C     Amplitude(s) for diagram number 50
      CALL FFV2_0(W(1,5),W(1,12),W(1,20),GC_67,AMP(50))
      CALL FFV1P0_3(W(1,1),W(1,6),GC_3,ZERO,ZERO,W(1,20))
      CALL VVV1P0_2(W(1,20),W(1,3),GC_4,MDL_MW,MDL_WW,W(1,16))
C     Amplitude(s) for diagram number 51
      CALL FFV2_0(W(1,10),W(1,2),W(1,16),GC_67,AMP(51))
      CALL FFV1_1(W(1,2),W(1,20),GC_3,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 52
      CALL FFV2_0(W(1,10),W(1,21),W(1,3),GC_67,AMP(52))
      CALL FFV2_4P0_3(W(1,1),W(1,6),GC_68,GC_77,MDL_MZ,MDL_WZ,W(1,18))
      CALL VVV1P0_1(W(1,3),W(1,18),GC_71,MDL_MW,MDL_WW,W(1,19))
C     Amplitude(s) for diagram number 53
      CALL FFV2_0(W(1,10),W(1,2),W(1,19),GC_67,AMP(53))
      CALL FFV2_4_1(W(1,2),W(1,18),GC_68,GC_77,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 54
      CALL FFV2_0(W(1,10),W(1,17),W(1,3),GC_67,AMP(54))
C     Amplitude(s) for diagram number 55
      CALL FFV2_0(W(1,10),W(1,9),W(1,18),GC_80,AMP(55))
C     Amplitude(s) for diagram number 56
      CALL VVVV2_0(W(1,20),W(1,8),W(1,4),W(1,3),GC_5,AMP(56))
C     Amplitude(s) for diagram number 57
      CALL VVV1_0(W(1,8),W(1,4),W(1,16),GC_4,AMP(57))
      CALL VVS1_3(W(1,20),W(1,3),GC_93,MDL_MW,MDL_WW,W(1,23))
C     Amplitude(s) for diagram number 58
      CALL VVS1_0(W(1,8),W(1,4),W(1,23),GC_92,AMP(58))
      CALL VVV1P0_3(W(1,20),W(1,4),GC_4,MDL_MW,MDL_WW,W(1,24))
C     Amplitude(s) for diagram number 59
      CALL VVV1_0(W(1,8),W(1,24),W(1,3),GC_4,AMP(59))
      CALL VVS1_3(W(1,20),W(1,4),GC_92,MDL_MW,MDL_WW,W(1,25))
C     Amplitude(s) for diagram number 60
      CALL VVS1_0(W(1,8),W(1,3),W(1,25),GC_93,AMP(60))
C     Amplitude(s) for diagram number 61
      CALL VVVV5_0(W(1,20),W(1,4),W(1,3),W(1,11),GC_75,AMP(61))
C     Amplitude(s) for diagram number 62
      CALL VVV1_0(W(1,4),W(1,16),W(1,11),GC_71,AMP(62))
C     Amplitude(s) for diagram number 63
      CALL VVS1_0(W(1,4),W(1,11),W(1,23),GC_85,AMP(63))
C     Amplitude(s) for diagram number 64
      CALL VVV1_0(W(1,24),W(1,3),W(1,11),GC_71,AMP(64))
C     Amplitude(s) for diagram number 65
      CALL VVS1_0(W(1,3),W(1,11),W(1,25),GC_84,AMP(65))
C     Amplitude(s) for diagram number 66
      CALL VVVV5_0(W(1,8),W(1,4),W(1,3),W(1,18),GC_75,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL VVV1_0(W(1,8),W(1,4),W(1,19),GC_4,AMP(67))
      CALL VVS1_3(W(1,3),W(1,18),GC_84,MDL_MW,MDL_WW,W(1,25))
C     Amplitude(s) for diagram number 68
      CALL VVS1_0(W(1,8),W(1,4),W(1,25),GC_92,AMP(68))
      CALL VVV1P0_2(W(1,4),W(1,18),GC_71,MDL_MW,MDL_WW,W(1,23))
C     Amplitude(s) for diagram number 69
      CALL VVV1_0(W(1,8),W(1,23),W(1,3),GC_4,AMP(69))
      CALL VVS1_3(W(1,4),W(1,18),GC_85,MDL_MW,MDL_WW,W(1,16))
C     Amplitude(s) for diagram number 70
      CALL VVS1_0(W(1,8),W(1,3),W(1,16),GC_93,AMP(70))
C     Amplitude(s) for diagram number 71
      CALL VVVV2_0(W(1,4),W(1,3),W(1,18),W(1,11),GC_54,AMP(71))
C     Amplitude(s) for diagram number 72
      CALL VVV1_0(W(1,4),W(1,19),W(1,11),GC_71,AMP(72))
C     Amplitude(s) for diagram number 73
      CALL VVS1_0(W(1,4),W(1,11),W(1,25),GC_85,AMP(73))
C     Amplitude(s) for diagram number 74
      CALL VVV1_0(W(1,23),W(1,3),W(1,11),GC_71,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL VVS1_0(W(1,3),W(1,11),W(1,16),GC_84,AMP(75))
C     Amplitude(s) for diagram number 76
      CALL VVS1_0(W(1,18),W(1,11),W(1,7),GC_99,AMP(76))
      CALL FFV1_2(W(1,5),W(1,20),GC_3,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 77
      CALL FFV1_0(W(1,7),W(1,2),W(1,22),GC_3,AMP(77))
C     Amplitude(s) for diagram number 78
      CALL FFV1_0(W(1,5),W(1,21),W(1,22),GC_3,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL FFV2_4_0(W(1,7),W(1,2),W(1,14),GC_68,GC_77,AMP(79))
C     Amplitude(s) for diagram number 80
      CALL FFV2_4_0(W(1,5),W(1,21),W(1,14),GC_68,GC_77,AMP(80))
      CALL FFV2_4_2(W(1,5),W(1,18),GC_68,GC_77,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 81
      CALL FFV1_0(W(1,21),W(1,2),W(1,22),GC_3,AMP(81))
C     Amplitude(s) for diagram number 82
      CALL FFV1_0(W(1,5),W(1,17),W(1,22),GC_3,AMP(82))
C     Amplitude(s) for diagram number 83
      CALL FFV2_4_0(W(1,21),W(1,2),W(1,14),GC_68,GC_77,AMP(83))
C     Amplitude(s) for diagram number 84
      CALL FFV2_4_0(W(1,5),W(1,17),W(1,14),GC_68,GC_77,AMP(84))
C     Amplitude(s) for diagram number 85
      CALL FFV2_0(W(1,7),W(1,9),W(1,4),GC_67,AMP(85))
C     Amplitude(s) for diagram number 86
      CALL FFV2_0(W(1,5),W(1,9),W(1,24),GC_67,AMP(86))
C     Amplitude(s) for diagram number 87
      CALL FFV2_0(W(1,21),W(1,9),W(1,4),GC_67,AMP(87))
C     Amplitude(s) for diagram number 88
      CALL FFV2_0(W(1,5),W(1,9),W(1,23),GC_67,AMP(88))
      CALL FFV2P0_3(W(1,1),W(1,9),GC_67,MDL_MW,MDL_WW,W(1,23))
C     Amplitude(s) for diagram number 89
      CALL FFV2_0(W(1,10),W(1,6),W(1,23),GC_67,AMP(89))
      CALL FFV2P0_3(W(1,1),W(1,12),GC_67,MDL_MW,MDL_WW,W(1,5))
C     Amplitude(s) for diagram number 90
      CALL FFV2_0(W(1,10),W(1,2),W(1,5),GC_67,AMP(90))
      CALL FFV1_2(W(1,1),W(1,8),GC_3,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 91
      CALL FFV1_0(W(1,10),W(1,6),W(1,22),GC_3,AMP(91))
      CALL FFV1_2(W(1,1),W(1,22),GC_3,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 92
      CALL FFV1_0(W(1,21),W(1,6),W(1,8),GC_3,AMP(92))
C     Amplitude(s) for diagram number 93
      CALL FFV2_4_0(W(1,10),W(1,6),W(1,14),GC_68,GC_77,AMP(93))
      CALL FFV2_4_2(W(1,1),W(1,14),GC_68,GC_77,ZERO,ZERO,W(1,24))
C     Amplitude(s) for diagram number 94
      CALL FFV1_0(W(1,24),W(1,6),W(1,8),GC_3,AMP(94))
      CALL FFV2_4_2(W(1,1),W(1,11),GC_68,GC_77,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 95
      CALL FFV1_0(W(1,7),W(1,6),W(1,22),GC_3,AMP(95))
C     Amplitude(s) for diagram number 96
      CALL FFV2_4_0(W(1,21),W(1,6),W(1,11),GC_68,GC_77,AMP(96))
C     Amplitude(s) for diagram number 97
      CALL FFV2_4_0(W(1,7),W(1,6),W(1,14),GC_68,GC_77,AMP(97))
C     Amplitude(s) for diagram number 98
      CALL FFV2_4_0(W(1,24),W(1,6),W(1,11),GC_68,GC_77,AMP(98))
C     Amplitude(s) for diagram number 99
      CALL FFV2_0(W(1,10),W(1,12),W(1,4),GC_67,AMP(99))
C     Amplitude(s) for diagram number 100
      CALL VVV1_0(W(1,8),W(1,4),W(1,5),GC_4,AMP(100))
C     Amplitude(s) for diagram number 101
      CALL FFV2_0(W(1,7),W(1,12),W(1,4),GC_67,AMP(101))
C     Amplitude(s) for diagram number 102
      CALL VVV1_0(W(1,4),W(1,5),W(1,11),GC_71,AMP(102))
      CALL FFV1_2(W(1,1),W(1,13),GC_3,ZERO,ZERO,W(1,5))
C     Amplitude(s) for diagram number 103
      CALL FFV1_0(W(1,5),W(1,2),W(1,22),GC_3,AMP(103))
C     Amplitude(s) for diagram number 104
      CALL FFV1_0(W(1,21),W(1,2),W(1,13),GC_3,AMP(104))
C     Amplitude(s) for diagram number 105
      CALL FFV2_4_0(W(1,5),W(1,2),W(1,14),GC_68,GC_77,AMP(105))
C     Amplitude(s) for diagram number 106
      CALL FFV1_0(W(1,24),W(1,2),W(1,13),GC_3,AMP(106))
      CALL FFV2_4_2(W(1,1),W(1,15),GC_68,GC_77,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 107
      CALL FFV1_0(W(1,11),W(1,2),W(1,22),GC_3,AMP(107))
C     Amplitude(s) for diagram number 108
      CALL FFV2_4_0(W(1,21),W(1,2),W(1,15),GC_68,GC_77,AMP(108))
C     Amplitude(s) for diagram number 109
      CALL FFV2_4_0(W(1,11),W(1,2),W(1,14),GC_68,GC_77,AMP(109))
C     Amplitude(s) for diagram number 110
      CALL FFV2_4_0(W(1,24),W(1,2),W(1,15),GC_68,GC_77,AMP(110))
C     Amplitude(s) for diagram number 111
      CALL FFV2_0(W(1,5),W(1,9),W(1,4),GC_67,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL VVV1_0(W(1,13),W(1,4),W(1,23),GC_4,AMP(112))
C     Amplitude(s) for diagram number 113
      CALL FFV2_0(W(1,11),W(1,9),W(1,4),GC_67,AMP(113))
C     Amplitude(s) for diagram number 114
      CALL VVV1_0(W(1,4),W(1,23),W(1,15),GC_71,AMP(114))
C     JAMPs contributing to orders QCD=3 QED=1
      JAMP(1,1)=+AMP(39)+AMP(40)-AMP(77)-AMP(78)-AMP(91)-AMP(92)+AMP
     $ (103)+AMP(104)
C     JAMPs contributing to orders QCD=2 QED=2
      JAMP(1,2)=-AMP(1)+AMP(6)+AMP(14)+AMP(18)+AMP(19)+AMP(20)+AMP(21)
     $ +AMP(22)+AMP(41)+AMP(42)+AMP(47)-AMP(52)-AMP(56)-AMP(57)-AMP(58)
     $ -AMP(59)-AMP(60)-AMP(79)-AMP(80)-AMP(85)-AMP(93)-AMP(94)-AMP(99)
     $ +AMP(105)+AMP(106)+AMP(111)
C     JAMPs contributing to orders QCD=1 QED=3
      JAMP(1,3)=-AMP(2)+AMP(7)+AMP(13)+AMP(23)+AMP(24)+AMP(25)+AMP(26)
     $ +AMP(27)+AMP(28)+AMP(29)+AMP(30)+AMP(31)+AMP(32)+AMP(43)+AMP(44)
     $ +AMP(48)-AMP(51)-AMP(61)-AMP(62)-AMP(63)-AMP(64)-AMP(65)-AMP(66)
     $ -AMP(67)-AMP(68)-AMP(69)-AMP(70)-AMP(81)-AMP(82)-AMP(86)-AMP(95)
     $ -AMP(96)-AMP(100)+AMP(107)+AMP(108)+AMP(112)
C     JAMPs contributing to orders QCD=0 QED=4
      JAMP(1,4)=-AMP(3)-AMP(4)-AMP(5)+AMP(8)+AMP(9)+AMP(10)-AMP(11)
     $ +AMP(12)+AMP(15)+AMP(16)+AMP(17)+AMP(33)+AMP(34)+AMP(35)+AMP(36)
     $ +AMP(37)+AMP(38)+AMP(45)+AMP(46)+AMP(49)+AMP(50)-AMP(53)-AMP(54)
     $ -AMP(55)-AMP(71)-AMP(72)-AMP(73)-AMP(74)-AMP(75)-AMP(76)-AMP(83)
     $ -AMP(84)-AMP(87)-AMP(88)+AMP(89)-AMP(90)-AMP(97)-AMP(98)-AMP
     $ (101)-AMP(102)+AMP(109)+AMP(110)+AMP(113)+AMP(114)


      AMP2=0D0
      SUM_AMP2=0D0
      DO I=1,NGRAPHS
        AMP2(I)=AMP2(I)+AMP(I)*DCONJG(AMP(I))
        SUM_AMP2 = SUM_AMP2 + AMP2(I)
      ENDDO
C     Normalization
      AMP2(:)=AMP2(:)/SUM_AMP2

      RES = 0.D0
      DO M = 1, NAMPSO
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
            ZTEMP = ZTEMP + CF(J,I)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            SQSOIND = SQSOINDEX(M,N)
            RES(SQSOIND) = RES(SQSOIND) + ZTEMP*DCONJG(JAMP(I,N))
     $       /DENOM(I)
          ENDDO
        ENDDO
      ENDDO

      END

      SUBROUTINE GET_ME(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE INITIALISE(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
C     USE SETPARA2 and not SETPARA so that ident_card.dat can be
C      automatically found
      CALL SETPARA2(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NCOMB
      PARAMETER (NCOMB=144)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/BORN_HEL_CONFIGS/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END





C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=2, NSQUAREDSO=7, NAMPSO=4)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  2) /    3,    1/
      DATA (AMPSPLITORDERS(  2,I),I=  1,  2) /    2,    2/
      DATA (AMPSPLITORDERS(  3,I),I=  1,  2) /    1,    3/
      DATA (AMPSPLITORDERS(  4,I),I=  1,  2) /    0,    4/
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)+AMPSPLITORDERS
     $   (ORDERINDEXB,I)
      ENDDO
      SQSOINDEX=SOINDEX_FOR_SQUARED_ORDERS(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=2, NSQSO=7, NAMPSO=4)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  2) /    6,    2/
      DATA (SQSPLITORDERS(  2,I),I=  1,  2) /    5,    3/
      DATA (SQSPLITORDERS(  3,I),I=  1,  2) /    4,    4/
      DATA (SQSPLITORDERS(  4,I),I=  1,  2) /    3,    5/
      DATA (SQSPLITORDERS(  5,I),I=  1,  2) /    2,    6/
      DATA (SQSPLITORDERS(  6,I),I=  1,  2) /    1,    7/
      DATA (SQSPLITORDERS(  7,I),I=  1,  2) /    0,    8/
      COMMON/ALL_SQSPLITORDERS/SQSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=7)

      INTEGER NSQSO
CF2PY INTENT(OUT) :: NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=2, NSQSO=7)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
CF2PY INTENT(IN) :: SOINDEX
CF2PY INTENT(OUT) :: ORDERS
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      COMMON/ALL_SQSPLITORDERS/SQSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_SQUARED_ORDERS_FOR_SOIN'
     $ //'DEX'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=2, NAMPSO=4)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=2, NAMPSO=4)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

C     --------
C     Now defining F2PY hooks.
C     --------

      SUBROUTINE GET_SPLIT_ORDER_NAMES(SONAMES)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NSO
      PARAMETER (NSO=2)
C     ARGUMENTS
C     
      CHARACTER*100 SONAMES(NSO)
      INTEGER IDX
CF2PY INTENT(OUT) :: SONAMES
C     
C     BEGIN CODE
C     
      SONAMES(1)='QCD'
      SONAMES(2)='QED'

      END


