C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,4)*Metric(2,3) + Metric(1,3)*Metric(2,4) -
C      2*Metric(1,2)*Metric(3,4)
C     
      SUBROUTINE VVVV2P0_4(V1, V2, V3, COUP, M4, W4,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 TMP10
      REAL*8 W4
      COMPLEX*16 V4(6)
      COMPLEX*16 DENOM
      COMPLEX*16 TMP4
      REAL*8 M4
      REAL*8 P4(0:3)
      COMPLEX*16 COUP
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP8
      V4(1) = +V1(1)+V2(1)+V3(1)
      V4(2) = +V1(2)+V2(2)+V3(2)
      P4(0) = -DBLE(V4(1))
      P4(1) = -DBLE(V4(2))
      P4(2) = -DIMAG(V4(2))
      P4(3) = -DIMAG(V4(1))
      TMP4 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP10 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      TMP8 = (V3(3)*V1(3)-V3(4)*V1(4)-V3(5)*V1(5)-V3(6)*V1(6))
      DENOM = COUP/(P4(0)**2-P4(1)**2-P4(2)**2-P4(3)**2 - M4 * (M4 
     $ -CI* W4))
      V4(3)= DENOM*(-1D0)*(-2D0 * CI*(V3(3)*TMP4)+CI*(V1(3)*TMP10+V2(3)
     $ *TMP8))
      V4(4)= DENOM*(-1D0)*(-2D0 * CI*(V3(4)*TMP4)+CI*(V1(4)*TMP10+V2(4)
     $ *TMP8))
      V4(5)= DENOM*(-1D0)*(-2D0 * CI*(V3(5)*TMP4)+CI*(V1(5)*TMP10+V2(5)
     $ *TMP8))
      V4(6)= DENOM*(-1D0)*(-2D0 * CI*(V3(6)*TMP4)+CI*(V1(6)*TMP10+V2(6)
     $ *TMP8))
      END


