ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_qcd_qed_sm-muon'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'UV_GQQt = ', UV_GQQT
      WRITE(*,2) 'UV_tMass = ', UV_TMASS
      WRITE(*,2) 'UVWfct_G_1 = ', UVWFCT_G_1
      WRITE(*,2) 'UVWfct_t_0 = ', UVWFCT_T_0
      WRITE(*,2) 'UV_GTTLEW = ', UV_GTTLEW
      WRITE(*,2) 'UV_GTTREW = ', UV_GTTREW
      WRITE(*,2) 'UV_GTTLEW_1eps = ', UV_GTTLEW_1EPS
      WRITE(*,2) 'UV_GTTREW_1eps = ', UV_GTTREW_1EPS
      WRITE(*,2) 'R2_UUA = ', R2_UUA
      WRITE(*,2) 'R2_DDZ_V3 = ', R2_DDZ_V3
      WRITE(*,2) 'R2_UUZ_V2 = ', R2_UUZ_V2
      WRITE(*,2) 'R2_GGZup = ', R2_GGZUP
      WRITE(*,2) 'R2_GGZdown = ', R2_GGZDOWN
      WRITE(*,2) 'R2_GGAAdown = ', R2_GGAADOWN
      WRITE(*,2) 'R2_GGAAup = ', R2_GGAAUP
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'R2_GQQ = ', R2_GQQ
      WRITE(*,2) 'R2_QQq = ', R2_QQQ
      WRITE(*,2) 'R2_QQt = ', R2_QQT
      WRITE(*,2) 'UV_GQQg_1eps = ', UV_GQQG_1EPS
      WRITE(*,2) 'UV_GQQq_1eps = ', UV_GQQQ_1EPS
      WRITE(*,2) 'UV_tMass_1eps = ', UV_TMASS_1EPS
      WRITE(*,2) 'UVWfct_G_1_1eps = ', UVWFCT_G_1_1EPS
      WRITE(*,2) 'UVWfct_t_0_1eps = ', UVWFCT_T_0_1EPS
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_39 = ', GC_39
      WRITE(*,2) 'GC_67 = ', GC_67
      WRITE(*,2) 'GC_68 = ', GC_68
      WRITE(*,2) 'GC_69 = ', GC_69
      WRITE(*,2) 'GC_71 = ', GC_71
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_85 = ', GC_85
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_93 = ', GC_93
      WRITE(*,2) 'GC_99 = ', GC_99
      WRITE(*,2) 'GC_116 = ', GC_116
